ecommerse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from ecommerse import settings


urlpatterns = [
    path('clientes/', include('modulos.clientes.urls')),
    path('mensualidad/', include('modulos.mensualidad.urls')),
    path('maquinaria/', include('modulos.maquinaria.urls')),
    path('instrumentos/', include('modulos.instrumentos.urls')),
    path('finanzas/', include('modulos.finanzas.urls')),
    path('', include('modulos.login.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modulos/clientes/urls.py
from django.urls import path
from modulos.clientes.views.cliente.views import *


app_name = "clientes"
urlpatterns = [
    path('detalle_cliente/', (DetalleCliente.as_view()), name='detalle_cliente'),
    path('crear_cliente/', (Addcliente.as_view()), name='crear_cliente'),
    path('editar_cliente/<int:pk>', (EditarCliente.as_view()), name='editar_cliente'),
    path('eliminar_cliente/<int:pk>', (EliminarCliente.as_view()), name='eliminar_cliente'),

]

modulos/clientes/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.utils.timezone import now
from ecommerse.constantes import Opciones

opciones = Opciones()
GENERO = opciones.genero()
MES = opciones.mes()


# Create your models here.


class Cliente(models.Model):
    nombre = models.CharField(unique=True, max_length=100)
    apellido = models.CharField(unique=True, max_length=100)
    genero = models.CharField(max_length=1, choices=GENERO, default=GENERO[0][1], blank=True, null=True)
    cedula = models.CharField(unique=True, max_length=10,
                              validators=[RegexValidator(regex='^.{10}$', message='Introduzca una cédula válida')],
                              default='')
    edad = models.IntegerField(default='')
    fecha_de_ingreso = models.DateField(default=now)

    def __str__(self):
        return "{} {}".format(self.nombre, self.apellido)

modulos/clientes/forms.py
from django import forms
from django.forms import ModelForm
from modulos.clientes.models import *

class ClienteForm(ModelForm):
    class Meta:
        model = Cliente
        fields ='__all__'
        widgets =  {
            'nombre':forms.TextInput(attrs={'class' : 'form-control', 'placeholder':'Ingrese su nombre','id':'inputNombre' } ),
            'apellido': forms.TextInput(attrs={'class' : 'form-control', 'placeholder':'Ingrese su apellido', 'id':'inputApellido'}),
            'genero': forms.Select(attrs= {'class': 'form-control', 'placeholder':'Seleccione su género', 'id':'inputGen' }),
            'cedula': forms.TextInput(attrs=
                                        {'class':'form-control',
                                         'placeholder':'Digite su número de cédula',
                                         'id':'inputCedula',
                                         }),
            'edad': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Digite su edad', 'id':'inputEdad'}),
            'fecha_de_ingreso': forms.DateInput(attrs={'class':'form-control','id':'fechIngr'})
        }

modulos/clientes/views/cliente/views.py
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import *
from modulos.clientes.models import *
from modulos.clientes.forms import *
from django.contrib.auth.mixins import LoginRequiredMixin

class DetalleCliente(LoginRequiredMixin, ListView):
    template_name = 'cliente/detalle_cliente.html'
    context_object_name = 'clientes'
    model = Cliente
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get("query")
        if query:
            parts = query.split()
            if len(parts) > 1:
                nombre = parts[0]
                apellido = ' '.join(parts[1:])
                return self.model.objects.filter(
                    nombre__icontains=nombre, apellido__icontains=apellido
                )
            else:
                return self.model.objects.filter(
                    Q(nombre__icontains=query) | Q(apellido__icontains=query)
                ) | self.model.objects.filter(cedula__icontains=query)
        else:
            return self.model.objects.all()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Registro de clientes'

        return context


class Addcliente(LoginRequiredMixin, CreateView):
    model = Cliente
    template_name = 'cliente/añadir_cliente.html'
    form_class = ClienteForm
    success_url = reverse_lazy("clientes:detalle_cliente")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Añadir Clientes'
        context['action_save'] = self.request.path
        context['url_anterior'] = '/clientes/detalle_cliente/'

        return context


class EditarCliente(LoginRequiredMixin, UpdateView):
    model = Cliente
    template_name = 'cliente/editar_cliente.html'
    success_url = reverse_lazy("clientes:detalle_cliente")
    form_class = ClienteForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'Edición de clientes'
        context['url_anterior'] = '/clientes/detalle_cliente'

        return context


class EliminarCliente(LoginRequiredMixin, DeleteView):
    model = Cliente
    template_name = 'cliente/eliminar_cliente.html'
    success_url = reverse_lazy("clientes:detalle_cliente")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'Eliminar cliente'
        context['url_anterior'] = '/clientes/detalle_cliente'
        context['listar_url'] = '/clientes/detalle_cliente'

        return context

modulos/clientes/templates/cliente/añadir_cliente.html
{% extends 'formulario_plantilla.html' %}
{% load static %}
{% block title %}
    <title> Registro de Clientes </title>
{% endblock %}


{% block formulario %}
    {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Error al Grabar</strong> {{ form.errors }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    {{ form.as_p }}

{% endblock %}
{% block js %}
    <script src= {% static "js/validaciones.js" %}></script>
{% endblock %}

modulos/clientes/templates/cliente/detalle_cliente.html
{% extends 'barlateral_mod_plantilla.html' %}
{% load static %}

{% block title %}
    <title> Clientes </title>
{% endblock %}

{% block contenido %}
    {% block search %}
        <form action="{% url 'clientes:detalle_cliente' %}" method="GET">
            <div class="input-group container mb-3">
                <input type="text" name="query" value="{{ query }}" class="form-control"
                       placeholder="Buscar cliente por nombre/apellido o cédula" id="idInputSearch"
                       aria-describedby="basic-addon2"/>
                <button type="submit" class="btn btn-primary mr-1" id="idSearchSp">Buscar</button>
            </div>
        </form>
    {% endblock %}

    <table class="container table table-responsive">
        <thead>
        <tr>
            <th> Nombre</th>
            <th> Apellido</th>
            <th> Genero</th>
            <th> Cedula</th>
            <th> Fecha de Ingreso</th>
            <th> Acciones</th>
        </tr>
        </thead>
        <tbody>

        {% for objects in clientes %}
            <tr>
                <td> {{ objects.nombre }} </td>
                <td> {{ objects.apellido }} </td>
                <td> {{ objects.genero }} </td>
                <td> {{ objects.cedula }} </td>
                <td> {{ objects.fecha_de_ingreso }} </td>
                <td>
                    <div class="btn-accion">
                        <div class="cab-tool">
                            <a class="text-decoration-none" href="{% url 'clientes:editar_cliente' objects.id %}">
                                <i class="ri-edit-2-line text-dark"></i>
                                <span class="tooltip-infor-icon"> Editar registro </span>
                            </a>
                        </div>

                        <div class="cab-tool">
                            <a class="text-decoration-none" href="{% url 'clientes:eliminar_cliente' objects.id %}">
                                <i class="ri-eraser-line text-dark"></i>
                                <span class="tooltip-infor-icon"> Eliminar registro </span>
                            </a>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>

    </table>

    <div class="mt-0">
        <a href="{% url 'clientes:crear_cliente' %}" class="btn btn-success btn-lg mt-md-5 me-md-auto ms-md-3">
            Añadir Cliente
        </a>
    </div>

{% endblock %}

modulos/clientes/templates/cliente/editar_cliente.html
{% extends 'formulario_plantilla.html' %}
{% load static %}
{% block title %}
    <title> Edición de Clientes </title>
{% endblock %}

{% block formulario %}
    {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Error al Grabar</strong> {{ form.errors }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    {{ form.as_p }}

{% endblock %}

modulos/clientes/templates/cliente/eliminar_cliente.html
{% extends 'formulario_plantilla.html' %}
{% load static %}
{% block title %}
    <title> Eliminación de clientes </title>
{% endblock %}

{% block formulario %}
    {% csrf_token %}
    <h3 style='text-align: center'>¿Estás seguro de eliminar el registro de "{{ object }}"?</h3>
{% endblock %}